"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { humanMutationFetch } from "./human-mutation";
import { StatusBadge } from "./status-badge";
import { RetentionCleanup } from "./retention-cleanup";

type Level = "ok" | "warning" | "attention" | "critical";
type Backup = { backupId: string; createdAt: string; schemaVersion: number; sizeBytes: number; integrity: string };
type Worktree = { taskId?: string; repoId: string; ageHours: number; sizeBytes: number; taskStatus?: string; dirty?: boolean; prState?: string; inventoryStatus: string; cleanupCandidate: boolean; classification: string };
export type OperationsOverviewView = { overall: "ready" | "attention" | "critical"; checkedAt: string; nextAction: string; database: { status: "ok" | "failed"; schema?: number; supportedMin?: number; supportedMax?: number; sizeBytes?: number; checkedAt: string }; backup: { level: Level; latest: (Backup & { ageHours: number }) | null; count: number; items: Backup[] }; disk: { level: Level; freeBytes: number; stateDbSize: number; backupSize: number; worktreeCreationAllowed: boolean }; sandbox: { status: "enforced" | "unavailable"; backend: string; version: string; privateHome: boolean; privateProc: boolean; privateTmp: boolean; validationNetwork: string; wslInterop: string }; providers: Array<{ provider: string; status: string; version?: string; previousVersion?: string; flagsCompatible: boolean; credentialStatus: string; sandboxCompatible: boolean; checkedAt: string; acknowledgedVersion?: string; versionChanged: boolean; identityChanged: boolean; reviewRequired: boolean; level: Level }>; maintenance: { state: "RUNNING" | "MAINTENANCE" | "DRAINING" | "OWNERSHIP_LOST" | "STOPPED"; activeCount: number }; activeOperations: Array<{ operationId: string; kind: string; taskId?: string; startedAt: string }>; unfinishedOperations: Array<{ operationId: string; type: string; taskId?: string; state: string; createdAt: string; errorCode?: string }>; reconcileRequired: number; worktrees: { count: number; totalSizeBytes: number; orphaned: number; cleanupCandidates: number; inventory: Worktree[] }; outbound: { unread: number; failed: number; ambiguous: number; pending: number; deliveredRecent: number; lastNotificationAt?: string; attention: Array<{ notificationId: string; taskId?: string; title: string; status: "failed" | "ambiguous" }> }; upgrade: { ready: boolean; reason: string } };
type Overview = OperationsOverviewView;
type Badge = "ready" | "ok" | "warning" | "attention" | "critical" | "enforced";

function Disclosure({ id, label, children, className = "" }: { id: string; label: string; children: ReactNode; className?: string }) {
  const [open, setOpen] = useState(false);
  return <div className={`disclosure ${className}`}><button type="button" className="secondary compactButton" aria-expanded={open} aria-controls={id} onClick={() => setOpen((value) => !value)}>{open ? "詳細を閉じる" : operationLabel(label)}</button><div id={id} hidden={!open}>{children}</div></div>;
}
function Card({ title, status, value, children }: { title: string; status: Badge; value: string; children?: ReactNode }) { return <article className="operationsCard"><div className="operationsCardHeading"><h3>{operationLabel(title)}</h3><StatusBadge status={status} /></div><strong className="operationsCardValue">{operationLabel(value)}</strong>{children}</article>; }

export function OperationalHealthPanel({ onOpenTask }: { onOpenTask?: (taskId: string) => void }) {
  const [overview, setOverview] = useState<Overview | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(""); const [filter, setFilter] = useState("all"); const [maintenanceDialog, setMaintenanceDialog] = useState(false);
  const refresh = useCallback(async () => { try { const response = await fetch("/api/operations/overview", { cache: "no-store" }); const data = await response.json() as Overview & { error?: string }; if (!response.ok) throw new Error(data.error || "運用状況を取得できませんでした。"); setOverview(data); setError(""); } catch (failure) { setError(failure instanceof Error ? failure.message : "運用状況を取得できませんでした。"); } }, []);
  useEffect(() => { const initial = window.setTimeout(() => void refresh(), 0); const timer = window.setInterval(() => void refresh(), 30_000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [refresh]);
  async function action(label: string, path: string, humanAction: Parameters<typeof humanMutationFetch>[1], init: RequestInit = {}, success?: string) { setBusy(label); setError(""); setNotice("処理中…"); try { const response = await humanMutationFetch(path, humanAction, init); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "操作に失敗しました。"); await refresh(); setNotice(success || "処理が完了しました。"); } catch (failure) { setNotice(""); setError(failure instanceof Error ? failure.message : "操作に失敗しました。"); } finally { setBusy(""); } }
  async function createBackup() { if (window.confirm("確認済みの状態バックアップを作成しますか？作業領域の復元・変更は行いません。")) await action("backup", "/api/state/backups", "state-backup", { method: "POST" }, "バックアップを作成し、検証しました。"); }
  async function cleanup(item: Worktree) { if (item.taskId && window.confirm("このクリーンな管理対象作業領域を削除しますか？タスク履歴は残り、ブランチやPRは削除しません。")) await action(`cleanup-${item.taskId}`, `/api/tasks/${item.taskId}`, "task-delete", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmedPrCleanup: true }) }); }
  const inventory = useMemo(() => overview?.worktrees.inventory.filter((item) => filter === "all" || (filter === "cleanup" && item.cleanupCandidate) || (filter === "dirty" && item.dirty) || (filter === "orphaned" && item.inventoryStatus === "orphaned_filesystem") || (filter === "missing" && item.inventoryStatus === "missing_filesystem") || (filter === "active" && item.taskStatus !== "archived")) ?? [], [filter, overview]); const attention = useMemo(() => overview ? attentionItems(overview) : [], [overview]);
  return <section className="operationsPanel" aria-labelledby="operations-heading">
    <div className="operationsTitle"><div><span className="eyebrow">ローカル運用画面</span><h2 id="operations-heading">運用状況</h2></div><div className="inlineActions">{notice ? <p className="actionResult actionResult-success" role="status">{notice}</p> : null}<button type="button" className="secondary" disabled={Boolean(busy)} onClick={() => { setNotice("運用状況を更新しています…"); void refresh().then(() => setNotice("運用状況を更新しました。")); }}>更新</button></div></div>
    <p className="actionAudience">操作できる人: 人。この画面の確認・バックアップ・整理・メンテナンス操作を行えます。エージェントは実行できません。</p>
    {!overview && !error ? <p className="operationsLoading" aria-live="polite">運用状況を読み込んでいます…</p> : null}{!overview && error ? <section className="operationsError" role="alert"><strong>運用状況を読み込めませんでした。</strong><p>{error}</p><button type="button" onClick={() => void refresh()}>再試行</button></section> : null}
    {overview ? <>
      <section className={`overallStatus ${overview.overall}`} aria-live="polite"><span>システム状態</span><strong>{overview.overall === "ready" ? "準備完了" : overview.overall === "critical" ? "重大" : "要対応"}</strong><p>{overview.overall === "ready" ? "確認が必要な運用項目はありません。" : `${attention.length}件の確認が必要です。`}</p>{attention.length ? <div className="nextActions"><b>次の操作</b><ul>{attention.slice(0, 3).map((item) => <li key={item.key}>{item.action}</li>)}</ul></div> : null}</section>
      <section aria-labelledby="status-summary"><h3 className="operationsSectionHeading" id="status-summary">概要</h3><div className="statusSummaryGrid"><Card title="データベース" status={overview.database.status === "ok" ? "ok" : "critical"} value={overview.database.status === "ok" ? "正常" : "失敗"}/><Card title="バックアップ" status={overview.backup.level} value={overview.backup.latest ? `${formatAge(overview.backup.latest.ageHours)}前` : "なし"}/><Card title="ディスク" status={overview.disk.level} value={`${formatBytes(overview.disk.freeBytes)}空き`}/><Card title="プロバイダー" status={overview.providers.every((item) => item.level === "ok") ? "ok" : "attention"} value={`${overview.providers.filter((item) => item.level === "ok").length} / ${overview.providers.length} 準備完了`}/><Card title="サンドボックス" status={overview.sandbox.status === "enforced" ? "enforced" : "critical"} value={overview.sandbox.status === "enforced" ? "適用中" : "利用不可"}/><Card title="未完了の操作" status={overview.reconcileRequired ? "attention" : "ok"} value={`${overview.reconcileRequired}件`}/></div></section>
      <section className="operationsSection" aria-labelledby="needs-attention"><h3 id="needs-attention">要確認</h3>{attention.length ? <div className="attentionList">{attention.map((item) => <article key={item.key}><StatusBadge status={item.level}/><div><strong>{item.title}</strong><p>{item.detail}</p></div>{item.taskId && onOpenTask ? <button type="button" className="secondary compactButton" onClick={() => onOpenTask(item.taskId!)}>問題を確認</button> : null}</article>)}</div> : <p className="emptyState">確認が必要な運用項目はありません。</p>}</section>
      <section className="operationsSection" aria-labelledby="system-health"><h3 id="system-health">システムの健全性</h3><div className="operationsDetailGrid"><Card title="データベース" status={overview.database.status === "ok" ? "ok" : "critical"} value={overview.database.status === "ok" ? "正常" : "失敗"}><Disclosure id="database-details" label="詳細を表示"><dl className="detailList"><div><dt>スキーマ</dt><dd>{overview.database.schema ?? "—"}</dd></div><div><dt>対応範囲</dt><dd>{overview.database.supportedMin}–{overview.database.supportedMax}</dd></div><div><dt>整合性</dt><dd>{overview.database.status === "ok" ? "正常" : "失敗"}</dd></div><div><dt>サイズ</dt><dd>{formatBytes(overview.database.sizeBytes ?? 0)}</dd></div><div><dt>最終確認</dt><dd>{relativeTime(overview.database.checkedAt)}</dd></div></dl></Disclosure></Card><Card title="OSサンドボックス" status={overview.sandbox.status === "enforced" ? "enforced" : "critical"} value={overview.sandbox.status === "enforced" ? "適用中" : "利用不可"}><ul className="featureList"><li>専用HOME</li><li>専用/proc</li><li>専用/tmp</li><li>検証ネットワークを遮断</li><li>WSL連携を遮断</li></ul><Disclosure id="sandbox-details" label="詳細を表示"><dl className="detailList"><div><dt>実行基盤</dt><dd>{overview.sandbox.backend}</dd></div><div><dt>バージョン</dt><dd>{overview.sandbox.version}</dd></div></dl></Disclosure></Card></div><div className="providerGrid" aria-label="プロバイダー診断">{overview.providers.map((provider) => <Card key={provider.provider} title={providerName(provider.provider)} status={provider.level} value={provider.status === "supported" ? "準備完了" : operationLabel(provider.status)}><Disclosure id={`provider-${provider.provider}`} label="詳細"><dl className="detailList"><div><dt>バージョン</dt><dd>{operationLabel(provider.version || "Unavailable")}</dd></div><div><dt>診断</dt><dd>{provider.status === "supported" ? "認証情報とサンドボックスを確認済み" : "タスク実行は停止中"}</dd></div></dl></Disclosure></Card>)}</div><div className="sectionActions"><button type="button" className="secondary" disabled={Boolean(busy)} onClick={() => void action("providers", "/api/operations/providers/refresh", "operations-provider-refresh", { method: "POST" })}>{busy === "providers" ? "診断を更新中…" : "プロバイダー診断を更新"}</button></div></section>
      <section className="operationsSection" aria-labelledby="operations-recovery"><h3 id="operations-recovery">運用と復旧</h3><div className="operationsDetailGrid"><Card title="バックアップ" status={overview.backup.level} value={overview.backup.latest ? "検証済み" : "不足"}><p className="cardHint">最終バックアップ: {overview.backup.latest ? `${formatAge(overview.backup.latest.ageHours)}前` : "なし"}</p><div className="inlineActions"><button type="button" disabled={Boolean(busy) || overview.maintenance.state !== "RUNNING"} onClick={() => void createBackup()}>{busy === "backup" ? "バックアップを作成中…" : "バックアップを作成"}</button></div><Disclosure id="backup-details" label="バックアップを表示">{overview.backup.items.length ? <div className="operationsRows">{overview.backup.items.map((backup) => <div key={backup.backupId}><span><code title={backup.backupId}>{shortId(backup.backupId)}</code> · 検証済み · スキーマ {backup.schemaVersion} · {formatBytes(backup.sizeBytes)} · {relativeTime(backup.createdAt)}</span><button type="button" className="secondary compactButton" disabled={Boolean(busy)} onClick={() => void action(`validate-${backup.backupId}`, `/api/state/backups/${backup.backupId}/validate`, "state-backup-validate", { method: "POST" }, "バックアップを検証しました。整合性・スキーマ・必須テーブル・権限を確認済みです。")}>{busy === `validate-${backup.backupId}` ? "検証中…" : "検証する"}</button></div>)}</div> : <p className="emptyState">バックアップはありません。</p>}</Disclosure></Card><Card title="未完了操作" status={overview.reconcileRequired ? "attention" : "ok"} value={overview.reconcileRequired ? `${overview.reconcileRequired}件を確認` : "未完了操作なし"}><Disclosure id="operation-details" label="詳細を表示">{overview.activeOperations.length || overview.unfinishedOperations.length ? <div className="operationsRows">{[...overview.activeOperations.map((item) => ({ ...item, state: "active", type: item.kind, createdAt: item.startedAt })), ...overview.unfinishedOperations].map((item) => <div key={item.operationId}><span><code title={item.operationId}>{shortId(item.operationId)}</code> · {operationLabel(item.type)} · {operationLabel(item.state)} · {relativeTime(item.createdAt)}</span>{item.taskId && onOpenTask ? <button type="button" className="textButton" onClick={() => onOpenTask(item.taskId!)}>問題を確認</button> : null}</div>)}</div> : <p className="emptyState">実行中・未完了の操作はありません。</p>}</Disclosure></Card></div></section>
      <section className="operationsSection" aria-labelledby="storage-worktrees"><h3 id="storage-worktrees">保存領域と作業領域</h3><div className="operationsDetailGrid"><Card title="ディスク" status={overview.disk.level} value={`${formatBytes(overview.disk.freeBytes)}空き`}><Disclosure id="disk-details" label="詳細を表示"><dl className="detailList"><div><dt>新しい作業領域</dt><dd>{overview.disk.worktreeCreationAllowed ? "許可" : "停止"}</dd></div><div><dt>バックアップ</dt><dd>{formatBytes(overview.disk.backupSize)}</dd></div><div><dt>状態データ</dt><dd>{formatBytes(overview.disk.stateDbSize)}</dd></div></dl></Disclosure></Card><Card title="作業領域" status={overview.worktrees.orphaned ? "attention" : "ok"} value={`${overview.worktrees.count}件`}><p className="cardHint">{overview.worktrees.cleanupCandidates} 整理候補 · {formatBytes(overview.worktrees.totalSizeBytes)}</p><Disclosure id="worktree-details" label="作業領域を表示"><div className="worktreeFilters" aria-label="作業領域の絞り込み">{[["all", "すべて"], ["active", "実行中"], ["cleanup", "整理候補"], ["dirty", "変更あり"], ["orphaned", "孤立"], ["missing", "不足"]].map(([value, label]) => <button key={value} type="button" className={filter === value ? "selectedFilter" : "secondary compactButton"} aria-pressed={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div>{inventory.length ? <div className="worktreeList">{inventory.map((item, index) => <article key={`${item.repoId}-${item.taskId ?? index}`}><div><strong>{item.repoId}</strong><span>{item.taskId ? shortId(item.taskId) : "未関連付け"} · {operationLabel(item.inventoryStatus)} · {formatBytes(item.sizeBytes)}</span></div><div className="inlineActions">{item.cleanupCandidate && item.taskId ? <button type="button" className="danger compactButton" disabled={Boolean(busy)} onClick={() => void cleanup(item)}>整理する</button> : item.taskId && onOpenTask ? <button type="button" className="secondary compactButton" onClick={() => onOpenTask(item.taskId!)}>問題を確認</button> : null}</div></article>)}</div> : <p className="emptyState">{filter === "orphaned" ? "孤立した作業領域はありません。" : "この条件に一致する作業領域はありません。"}</p>}</Disclosure></Card></div></section>
      <section className="operationsSection" aria-labelledby="notifications"><h3 id="notifications">通知</h3><Card title="Slack送信" status={overview.outbound.failed || overview.outbound.ambiguous ? "attention" : "ok"} value={overview.outbound.failed || overview.outbound.ambiguous ? `${overview.outbound.failed + overview.outbound.ambiguous} 要確認` : "正常"}><p className="cardHint">{overview.outbound.pending} 保留中 · {overview.outbound.deliveredRecent} 24時間以内に送信済み</p><Disclosure id="notification-details" label="詳細を表示">{overview.outbound.attention.length ? <div className="operationsRows">{overview.outbound.attention.map((item) => <div key={item.notificationId}><span><StatusBadge status="attention"/> {operationLabel(item.status)} · {item.title}</span><span className="inlineActions">{item.taskId && onOpenTask ? <button type="button" className="textButton" onClick={() => onOpenTask(item.taskId!)}>問題を確認</button> : null}<button type="button" className="secondary compactButton" disabled={Boolean(busy)} onClick={() => void action(`retry-${item.notificationId}`, `/api/notifications/${item.notificationId}/deliveries/slack/retry`, "outbound-retry", { method: "POST" })}>再試行</button>{item.status === "ambiguous" ? <><button type="button" className="danger compactButton" disabled={Boolean(busy)} onClick={() => void action(`delivered-${item.notificationId}`, `/api/notifications/${item.notificationId}/deliveries/slack/mark-delivered`, "outbound-mark-delivered", { method: "POST" })}>送信済みにする</button><button type="button" className="danger compactButton" disabled={Boolean(busy)} onClick={() => void action(`dismiss-${item.notificationId}`, `/api/notifications/${item.notificationId}/deliveries/slack/dismiss`, "outbound-dismiss", { method: "POST" })}>対象外にする</button></> : null}</span></div>)}</div> : <p className="emptyState">失敗した送信はありません。</p>}</Disclosure></Card></section>
      <RetentionCleanup />
      <section className="operationsSection maintenanceArea" aria-labelledby="maintenance"><h3 id="maintenance">メンテナンス</h3><p>{overview.maintenance.state === "RUNNING" ? "システムは正常に稼働しています。" : `システムは${maintenanceLabel(overview.maintenance.state)}。`}</p><div className="sectionActions">{overview.maintenance.state === "RUNNING" ? <button type="button" className="danger" disabled={Boolean(busy)} onClick={() => setMaintenanceDialog(true)}>メンテナンスモードに入る</button> : <button type="button" className="secondary" disabled={Boolean(busy)} onClick={() => void action("maintenance", "/api/maintenance", "maintenance-mode", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: false }) })}>通常運用に戻る</button>}</div></section>
      <section className="operationsSection runbook" aria-labelledby="runbook"><h3 id="runbook">運用手順</h3><nav aria-label="運用手順">{["毎日の開始", "アップグレード", "バックアップ / 復元", "プロバイダー障害", "サンドボックス障害", "データベース問題", "ディスク容量不足", "停止した操作"].map((item) => <a key={item} href={`#runbook-${item.toLowerCase().replaceAll(" ", "-").replaceAll("/", "-")}`}>{item}</a>)}</nav><p id="runbook-daily-start">毎日の開始: データベース、サンドボックス、プロバイダー、バックアップ、ディスク、未完了操作がないことを確認します。</p><p id="runbook-backup--restore">バックアップ / 復元: 復元はサーバー停止中にCLIで行う手順です。この画面は自動復元しません。</p></section>
      <Disclosure id="healthy-systems" label={`正常な項目を表示 (${healthyCount(overview)})`} className="healthySystems"><ul><li>データベースの準備状態はローカルで確認済みです。</li><li>サンドボックス分離は独立して適用されています。</li><li>自動修復・再試行・削除・復元は無効です。</li></ul></Disclosure>
    </> : null}{notice ? <p className="success" role="status">{notice}</p> : null}{overview && error ? <p className="error" role="alert">{error}</p> : null}{maintenanceDialog ? <div className="dialogBackdrop"><section className="cleanupDialog" role="dialog" aria-modal="true" aria-labelledby="maintenance-dialog-title" aria-describedby="maintenance-dialog-description"><span className="eyebrow">注意が必要な操作</span><h2 id="maintenance-dialog-title">メンテナンスモードに入りますか？</h2><p id="maintenance-dialog-description">新しいタスクの変更操作を停止し、実行中の操作が終わるのを待ちます。修復・整理・復元は実行しません。</p><div className="dialogActions"><button type="button" className="secondary" onClick={() => setMaintenanceDialog(false)}>キャンセル</button><button type="button" className="danger" disabled={busy === "maintenance"} onClick={() => { setMaintenanceDialog(false); void action("maintenance", "/api/maintenance", "maintenance-mode", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: true }) }); }}>メンテナンスモードに入る</button></div></section></div> : null}
  </section>;
}

export function attentionItems(overview: Overview) { const items: Array<{ key: string; level: "attention" | "critical"; title: string; detail: string; action: string; taskId?: string }> = []; if (overview.overall === "critical") items.push({ key: "system", level: "critical", title: "システム状態が重大", detail: "サンドボックスまたは基幹機能を確認してください。", action: overview.nextAction }); if (overview.reconcileRequired) items.push({ key: "reconcile", level: "attention", title: "未完了操作の確認が必要", detail: `${overview.reconcileRequired}件の操作を確認してください。`, action: "未完了操作を確認" }); if (overview.backup.level !== "ok") items.push({ key: "backup", level: "attention", title: "バックアップを確認", detail: overview.backup.latest ? `最後の検証から${formatAge(overview.backup.latest.ageHours)}経過しています。` : "検証済みバックアップがありません。", action: "バックアップを作成" }); if (overview.disk.level !== "ok") items.push({ key: "disk", level: "attention", title: "ディスク容量を確認", detail: `${formatBytes(overview.disk.freeBytes)}空きです。`, action: "ディスク容量を確認" }); if (overview.providers.some((provider) => provider.level !== "ok")) items.push({ key: "providers", level: "attention", title: "プロバイダーを確認", detail: "準備ができていないプロバイダーがあります。", action: "プロバイダー診断を更新" }); if (overview.worktrees.orphaned) items.push({ key: "worktrees", level: "attention", title: "作業領域を確認", detail: `${overview.worktrees.orphaned}件の作業領域に確認が必要です。`, action: "作業領域を確認" }); if (overview.outbound.failed || overview.outbound.ambiguous) items.push({ key: "slack", level: "attention", title: "Slack送信を確認", detail: `失敗${overview.outbound.failed}件 · 判定不能${overview.outbound.ambiguous}件`, action: "Slack送信を解決" }); return items; }
function healthyCount(overview: Overview) { return [overview.database.status === "ok", overview.backup.level === "ok", overview.disk.level === "ok", overview.sandbox.status === "enforced", overview.providers.every((item) => item.level === "ok"), !overview.reconcileRequired].filter(Boolean).length; }
function providerName(value: string) { return value === "codex" ? "Codex" : value === "cursor" ? "Cursor" : value === "claude" ? "Claude" : value; } function maintenanceLabel(value: string) { return ({ MAINTENANCE: "メンテナンス中", DRAINING: "停止準備中", OWNERSHIP_LOST: "管理権限を確認できません", STOPPED: "停止中" } as Record<string, string>)[value] ?? value; } function operationLabel(value: string) { const labels: Record<string, string> = { Database: "データベース", "OS Sandbox": "OSサンドボックス", Backup: "バックアップ", Reconciliation: "未完了操作", Disk: "ディスク", Worktrees: "作業領域", "Slack delivery": "Slack送信", Healthy: "正常", Missing: "なし", Verified: "検証済み", "No pending operations": "未完了操作なし", "No active or unfinished operations.": "実行中・未完了の操作はありません。", "Show details": "詳細を表示", "View backups": "バックアップを表示", "View worktrees": "作業領域を表示", Details: "詳細", Ready: "準備完了", ready: "準備完了", supported: "準備完了", version_probe_failed: "バージョン確認失敗", Unavailable: "未取得", unavailable: "利用不可", Enforced: "適用中", enforced: "適用中", OK: "正常", ok: "正常", FAILED: "失敗", failed: "失敗", ambiguous: "判定できない", active: "実行中", pending: "保留中", completed: "完了", orphaned_filesystem: "孤立", missing_filesystem: "不足" }; return labels[value] ?? (value.includes("probe") ? "バージョン確認失敗" : value); } function shortId(value: string) { return `${value.slice(0, 8)}…`; } function formatBytes(value: number) { if (value >= 1024 ** 3) return `${(value / 1024 ** 3).toFixed(1)} GB`; if (value >= 1024 ** 2) return `${(value / 1024 ** 2).toFixed(1)} MB`; return `${Math.max(0, Math.ceil(value / 1024))} KB`; } function formatAge(hours: number) { return hours < 1 ? `${Math.max(0, Math.floor(hours * 60))}分` : hours < 48 ? `${Math.floor(hours)}時間` : `${Math.floor(hours / 24)}日`; } function relativeTime(value: string) { return `${formatAge(Math.max(0, (Date.now() - Date.parse(value)) / 3_600_000))}前`; }
