"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { humanMutationFetch } from "./human-mutation";
import { StatusBadge } from "./status-badge";
import { RetentionCleanup } from "./retention-cleanup";

type Level = "ok" | "warning" | "attention" | "critical";
type Backup = { backupId: string; createdAt: string; schemaVersion: number; sizeBytes: number; integrity: string };
type Worktree = { taskId?: string; repoId: string; ageHours: number; sizeBytes: number; taskStatus?: string; dirty?: boolean; prState?: string; inventoryStatus: string; cleanupCandidate: boolean; classification: string };
export type OperationsOverviewView = { overall: "ready" | "attention" | "critical"; checkedAt: string; nextAction: string; database: { status: "ok" | "failed"; schema?: number; supportedMin?: number; supportedMax?: number; sizeBytes?: number; checkedAt: string }; backup: { level: Level; latest: (Backup & { ageHours: number }) | null; count: number; items: Backup[] }; disk: { level: Level; freeBytes: number; stateDbSize: number; backupSize: number; worktreeCreationAllowed: boolean }; sandbox: { status: "enforced" | "unavailable"; backend: string; version: string; privateHome: boolean; privateProc: boolean; privateTmp: boolean; validationNetwork: string; wslInterop: string }; providers: Array<{ provider: string; status: string; version?: string; level: Level }>; maintenance: { state: "RUNNING" | "DRAINING" | "STOPPED"; activeCount: number }; activeOperations: Array<{ operationId: string; kind: string; taskId?: string; startedAt: string }>; unfinishedOperations: Array<{ operationId: string; type: string; taskId?: string; state: string; createdAt: string; errorCode?: string }>; reconcileRequired: number; worktrees: { count: number; totalSizeBytes: number; orphaned: number; cleanupCandidates: number; inventory: Worktree[] }; outbound: { unread: number; failed: number; ambiguous: number; pending: number; deliveredRecent: number; lastNotificationAt?: string; attention: Array<{ notificationId: string; taskId?: string; title: string; status: "failed" | "ambiguous" }> }; upgrade: { ready: boolean; reason: string } };
type Overview = OperationsOverviewView;
type Badge = "ready" | "ok" | "warning" | "attention" | "critical" | "enforced";

function Disclosure({ id, label, children, className = "" }: { id: string; label: string; children: ReactNode; className?: string }) {
  const [open, setOpen] = useState(false);
  return <div className={`disclosure ${className}`}><button type="button" className="secondary compactButton" aria-expanded={open} aria-controls={id} onClick={() => setOpen((value) => !value)}>{open ? "Hide details" : label}</button><div id={id} hidden={!open}>{children}</div></div>;
}
function Card({ title, status, value, children }: { title: string; status: Badge; value: string; children?: ReactNode }) { return <article className="operationsCard"><div className="operationsCardHeading"><h3>{title}</h3><StatusBadge status={status} /></div><strong className="operationsCardValue">{value}</strong>{children}</article>; }

export function OperationalHealthPanel({ onOpenTask }: { onOpenTask?: (taskId: string) => void }) {
  const [overview, setOverview] = useState<Overview | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(""); const [filter, setFilter] = useState("all"); const [maintenanceDialog, setMaintenanceDialog] = useState(false);
  const refresh = useCallback(async () => { try { const response = await fetch("/api/operations/overview", { cache: "no-store" }); const data = await response.json() as Overview & { error?: string }; if (!response.ok) throw new Error(data.error || "Operations overview failed"); setOverview(data); setError(""); } catch (failure) { setError(failure instanceof Error ? failure.message : "Operations overview failed"); } }, []);
  useEffect(() => { const initial = window.setTimeout(() => void refresh(), 0); const timer = window.setInterval(() => void refresh(), 30_000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [refresh]);
  async function action(label: string, path: string, humanAction: Parameters<typeof humanMutationFetch>[1], init: RequestInit = {}, success?: string) { setBusy(label); setError(""); setNotice(""); try { const response = await humanMutationFetch(path, humanAction, init); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || `${label} failed`); await refresh(); if (success) setNotice(success); } catch (failure) { setError(failure instanceof Error ? failure.message : `${label} failed`); } finally { setBusy(""); } }
  async function createBackup() { if (window.confirm("Create a verified state backup? This does not restore or modify task worktrees.")) await action("backup", "/api/state/backups", "state-backup", { method: "POST" }, "Backup created — verified."); }
  async function cleanup(item: Worktree) { if (item.taskId && window.confirm("Delete this clean managed worktree? Task history remains, and no branch or pull request is deleted.")) await action(`cleanup-${item.taskId}`, `/api/tasks/${item.taskId}`, "task-delete", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmedPrCleanup: true }) }); }
  const inventory = useMemo(() => overview?.worktrees.inventory.filter((item) => filter === "all" || (filter === "cleanup" && item.cleanupCandidate) || (filter === "dirty" && item.dirty) || (filter === "orphaned" && item.inventoryStatus === "orphaned_filesystem") || (filter === "missing" && item.inventoryStatus === "missing_filesystem") || (filter === "active" && item.taskStatus !== "archived")) ?? [], [filter, overview]); const attention = useMemo(() => overview ? attentionItems(overview) : [], [overview]);
  return <section className="operationsPanel" aria-labelledby="operations-heading">
    <div className="operationsTitle"><div><span className="eyebrow">Local operations console</span><h2 id="operations-heading">Operations</h2></div><button type="button" className="secondary" disabled={Boolean(busy)} onClick={() => void refresh()}>Refresh status</button></div>
    {!overview && !error ? <p className="operationsLoading" aria-live="polite">Loading system status…</p> : null}{!overview && error ? <section className="operationsError" role="alert"><strong>Operations status could not be loaded.</strong><p>{error}</p><button type="button" onClick={() => void refresh()}>Retry</button></section> : null}
    {overview ? <>
      <section className={`overallStatus ${overview.overall}`} aria-live="polite"><span>System status</span><strong>{overview.overall === "ready" ? "READY" : overview.overall === "critical" ? "CRITICAL" : "ATTENTION REQUIRED"}</strong><p>{overview.overall === "ready" ? "No operations require attention." : `${attention.length} ${attention.length === 1 ? "item needs" : "items need"} review.`}</p>{attention.length ? <div className="nextActions"><b>Next actions</b><ul>{attention.slice(0, 3).map((item) => <li key={item.key}>{item.action}</li>)}</ul></div> : null}</section>
      <section aria-labelledby="status-summary"><h3 className="operationsSectionHeading" id="status-summary">Status</h3><div className="statusSummaryGrid"><Card title="Database" status={overview.database.status === "ok" ? "ok" : "critical"} value={overview.database.status === "ok" ? "OK" : "FAILED"}/><Card title="Backup" status={overview.backup.level} value={overview.backup.latest ? `${formatAge(overview.backup.latest.ageHours)} ago` : "Missing"}/><Card title="Disk" status={overview.disk.level} value={`${formatBytes(overview.disk.freeBytes)} free`}/><Card title="Providers" status={overview.providers.every((item) => item.level === "ok") ? "ok" : "attention"} value={`${overview.providers.filter((item) => item.level === "ok").length} / ${overview.providers.length} ready`}/><Card title="Sandbox" status={overview.sandbox.status === "enforced" ? "enforced" : "critical"} value={overview.sandbox.status === "enforced" ? "Enforced" : "Unavailable"}/><Card title="Operations" status={overview.reconcileRequired ? "attention" : "ok"} value={`${overview.reconcileRequired} pending`}/></div></section>
      <section className="operationsSection" aria-labelledby="needs-attention"><h3 id="needs-attention">Needs Attention</h3>{attention.length ? <div className="attentionList">{attention.map((item) => <article key={item.key}><StatusBadge status={item.level}/><div><strong>{item.title}</strong><p>{item.detail}</p></div>{item.taskId && onOpenTask ? <button type="button" className="secondary compactButton" onClick={() => onOpenTask(item.taskId!)}>Review issue</button> : null}</article>)}</div> : <p className="emptyState">No operations require attention.</p>}</section>
      <section className="operationsSection" aria-labelledby="system-health"><h3 id="system-health">System Health</h3><div className="operationsDetailGrid"><Card title="Database" status={overview.database.status === "ok" ? "ok" : "critical"} value={overview.database.status === "ok" ? "OK" : "FAILED"}><Disclosure id="database-details" label="Show details"><dl className="detailList"><div><dt>Schema</dt><dd>{overview.database.schema ?? "—"}</dd></div><div><dt>Supported</dt><dd>{overview.database.supportedMin}–{overview.database.supportedMax}</dd></div><div><dt>Integrity</dt><dd>{overview.database.status === "ok" ? "OK" : "Failed"}</dd></div><div><dt>Size</dt><dd>{formatBytes(overview.database.sizeBytes ?? 0)}</dd></div><div><dt>Last checked</dt><dd>{relativeTime(overview.database.checkedAt)}</dd></div></dl></Disclosure></Card><Card title="OS Sandbox" status={overview.sandbox.status === "enforced" ? "enforced" : "critical"} value={overview.sandbox.status === "enforced" ? "Enforced" : "Unavailable"}><ul className="featureList"><li>Private HOME</li><li>Private /proc</li><li>Private /tmp</li><li>Validation network blocked</li><li>WSL interop blocked</li></ul><Disclosure id="sandbox-details" label="Show details"><dl className="detailList"><div><dt>Backend</dt><dd>{overview.sandbox.backend}</dd></div><div><dt>Version</dt><dd>{overview.sandbox.version}</dd></div></dl></Disclosure></Card></div><div className="providerGrid" aria-label="Provider diagnostics">{overview.providers.map((provider) => <Card key={provider.provider} title={providerName(provider.provider)} status={provider.level} value={provider.status === "supported" ? "Ready" : provider.status}><Disclosure id={`provider-${provider.provider}`} label="Details"><dl className="detailList"><div><dt>Version</dt><dd>{provider.version || "Unavailable"}</dd></div><div><dt>Diagnostic</dt><dd>{provider.status === "supported" ? "Credential and sandbox checks passed" : "Task execution is blocked"}</dd></div></dl></Disclosure></Card>)}</div><div className="sectionActions"><button type="button" className="secondary" disabled={Boolean(busy)} onClick={() => void action("providers", "/api/operations/providers/refresh", "operations-provider-refresh", { method: "POST" })}>{busy === "providers" ? "Refreshing diagnostics…" : "Refresh provider diagnostics"}</button></div></section>
      <section className="operationsSection" aria-labelledby="operations-recovery"><h3 id="operations-recovery">Operations &amp; Recovery</h3><div className="operationsDetailGrid"><Card title="Backup" status={overview.backup.level} value={overview.backup.latest ? "Verified" : "Missing"}><p className="cardHint">Last backup: {overview.backup.latest ? `${formatAge(overview.backup.latest.ageHours)} ago` : "none"}</p><div className="inlineActions"><button type="button" disabled={Boolean(busy) || overview.maintenance.state !== "RUNNING"} onClick={() => void createBackup()}>{busy === "backup" ? "Creating backup…" : "Create Backup"}</button></div><Disclosure id="backup-details" label="View backups">{overview.backup.items.length ? <div className="operationsRows">{overview.backup.items.map((backup) => <div key={backup.backupId}><span><code title={backup.backupId}>{shortId(backup.backupId)}</code> · verified · schema {backup.schemaVersion} · {formatBytes(backup.sizeBytes)} · {relativeTime(backup.createdAt)}</span><button type="button" className="secondary compactButton" disabled={Boolean(busy)} onClick={() => void action(`validate-${backup.backupId}`, `/api/state/backups/${backup.backupId}/validate`, "state-backup-validate", { method: "POST" }, "Backup validation passed — integrity, schema, required tables, and permissions verified.")}>{busy === `validate-${backup.backupId}` ? "Validating…" : "Validate"}</button></div>)}</div> : <p className="emptyState">No backups recorded.</p>}</Disclosure></Card><Card title="Reconciliation" status={overview.reconcileRequired ? "attention" : "ok"} value={overview.reconcileRequired ? `${overview.reconcileRequired} require review` : "No pending operations"}><Disclosure id="operation-details" label="Show details">{overview.activeOperations.length || overview.unfinishedOperations.length ? <div className="operationsRows">{[...overview.activeOperations.map((item) => ({ ...item, state: "active", type: item.kind, createdAt: item.startedAt })), ...overview.unfinishedOperations].map((item) => <div key={item.operationId}><span><code title={item.operationId}>{shortId(item.operationId)}</code> · {item.type} · {item.state} · {relativeTime(item.createdAt)}</span>{item.taskId && onOpenTask ? <button type="button" className="textButton" onClick={() => onOpenTask(item.taskId!)}>Review issue</button> : null}</div>)}</div> : <p className="emptyState">No active or unfinished operations.</p>}</Disclosure></Card></div></section>
      <section className="operationsSection" aria-labelledby="storage-worktrees"><h3 id="storage-worktrees">Storage &amp; Worktrees</h3><div className="operationsDetailGrid"><Card title="Disk" status={overview.disk.level} value={`${formatBytes(overview.disk.freeBytes)} free`}><Disclosure id="disk-details" label="Show details"><dl className="detailList"><div><dt>New worktrees</dt><dd>{overview.disk.worktreeCreationAllowed ? "Allowed" : "Blocked"}</dd></div><div><dt>Backups</dt><dd>{formatBytes(overview.disk.backupSize)}</dd></div><div><dt>State data</dt><dd>{formatBytes(overview.disk.stateDbSize)}</dd></div></dl></Disclosure></Card><Card title="Worktrees" status={overview.worktrees.orphaned ? "attention" : "ok"} value={`${overview.worktrees.count} total`}><p className="cardHint">{overview.worktrees.cleanupCandidates} cleanup candidates · {formatBytes(overview.worktrees.totalSizeBytes)}</p><Disclosure id="worktree-details" label="View worktrees"><div className="worktreeFilters" aria-label="Worktree filters">{[["all", "All"], ["active", "Active"], ["cleanup", "Cleanup candidates"], ["dirty", "Dirty"], ["orphaned", "Orphaned"], ["missing", "Missing"]].map(([value, label]) => <button key={value} type="button" className={filter === value ? "selectedFilter" : "secondary compactButton"} aria-pressed={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div>{inventory.length ? <div className="worktreeList">{inventory.map((item, index) => <article key={`${item.repoId}-${item.taskId ?? index}`}><div><strong>{item.repoId}</strong><span>{item.taskId ? shortId(item.taskId) : "Unlinked"} · {item.inventoryStatus} · {formatBytes(item.sizeBytes)}</span></div><div className="inlineActions">{item.cleanupCandidate && item.taskId ? <button type="button" className="danger compactButton" disabled={Boolean(busy)} onClick={() => void cleanup(item)}>Cleanup</button> : item.taskId && onOpenTask ? <button type="button" className="secondary compactButton" onClick={() => onOpenTask(item.taskId!)}>Review issue</button> : null}</div></article>)}</div> : <p className="emptyState">{filter === "orphaned" ? "No orphaned worktrees." : "No worktrees match this filter."}</p>}</Disclosure></Card></div></section>
      <section className="operationsSection" aria-labelledby="notifications"><h3 id="notifications">Notifications</h3><Card title="Slack delivery" status={overview.outbound.failed || overview.outbound.ambiguous ? "attention" : "ok"} value={overview.outbound.failed || overview.outbound.ambiguous ? `${overview.outbound.failed + overview.outbound.ambiguous} need review` : "Healthy"}><p className="cardHint">{overview.outbound.pending} pending · {overview.outbound.deliveredRecent} delivered in 24h</p><Disclosure id="notification-details" label="Show details">{overview.outbound.attention.length ? <div className="operationsRows">{overview.outbound.attention.map((item) => <div key={item.notificationId}><span><StatusBadge status="attention"/> {item.status.toUpperCase()} · {item.title}</span><span className="inlineActions">{item.taskId && onOpenTask ? <button type="button" className="textButton" onClick={() => onOpenTask(item.taskId!)}>Review issue</button> : null}<button type="button" className="secondary compactButton" disabled={Boolean(busy)} onClick={() => void action(`retry-${item.notificationId}`, `/api/notifications/${item.notificationId}/deliveries/slack/retry`, "outbound-retry", { method: "POST" })}>Retry</button>{item.status === "ambiguous" ? <><button type="button" className="danger compactButton" disabled={Boolean(busy)} onClick={() => void action(`delivered-${item.notificationId}`, `/api/notifications/${item.notificationId}/deliveries/slack/mark-delivered`, "outbound-mark-delivered", { method: "POST" })}>Mark delivered</button><button type="button" className="danger compactButton" disabled={Boolean(busy)} onClick={() => void action(`dismiss-${item.notificationId}`, `/api/notifications/${item.notificationId}/deliveries/slack/dismiss`, "outbound-dismiss", { method: "POST" })}>Dismiss</button></> : null}</span></div>)}</div> : <p className="emptyState">No failed outbound deliveries.</p>}</Disclosure></Card></section>
      <RetentionCleanup />
      <section className="operationsSection maintenanceArea" aria-labelledby="maintenance"><h3 id="maintenance">Maintenance</h3><p>{overview.maintenance.state === "RUNNING" ? "System is running normally." : `System is ${overview.maintenance.state.toLowerCase()}.`}</p><div className="sectionActions">{overview.maintenance.state === "RUNNING" ? <button type="button" className="danger" disabled={Boolean(busy)} onClick={() => setMaintenanceDialog(true)}>Enter Maintenance Mode</button> : <button type="button" className="secondary" disabled={Boolean(busy)} onClick={() => void action("maintenance", "/api/maintenance", "maintenance-mode", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: false }) })}>Resume normal operation</button>}</div></section>
      <section className="operationsSection runbook" aria-labelledby="runbook"><h3 id="runbook">Runbook</h3><nav aria-label="Operations runbook">{["Daily Start", "Upgrade", "Backup / Restore", "Provider Failure", "Sandbox Failure", "Database Problem", "Disk Full", "Stuck Operation"].map((item) => <a key={item} href={`#runbook-${item.toLowerCase().replaceAll(" ", "-").replaceAll("/", "-")}`}>{item}</a>)}</nav><p id="runbook-daily-start">Daily Start: confirm a ready database, enforced sandbox, providers, backup, disk, and no reconciliation-required operations.</p><p id="runbook-backup--restore">Backup / Restore: restore is an offline, server-stopped CLI procedure; this dashboard never restores automatically.</p></section>
      <Disclosure id="healthy-systems" label={`Show healthy systems (${healthyCount(overview)})`} className="healthySystems"><ul><li>Database readiness is checked locally.</li><li>Sandbox isolation is independently enforced.</li><li>Automatic repair, retry, deletion, and restore are disabled.</li></ul></Disclosure>
    </> : null}{notice ? <p className="success" role="status">{notice}</p> : null}{overview && error ? <p className="error" role="alert">{error}</p> : null}{maintenanceDialog ? <div className="dialogBackdrop"><section className="cleanupDialog" role="dialog" aria-modal="true" aria-labelledby="maintenance-dialog-title" aria-describedby="maintenance-dialog-description"><span className="eyebrow">Dangerous operation</span><h2 id="maintenance-dialog-title">Enter maintenance mode?</h2><p id="maintenance-dialog-description">New task mutations will be blocked and running operations will be drained. This does not perform repair, cleanup, or restore.</p><div className="dialogActions"><button type="button" className="secondary" onClick={() => setMaintenanceDialog(false)}>Cancel</button><button type="button" className="danger" disabled={busy === "maintenance"} onClick={() => { setMaintenanceDialog(false); void action("maintenance", "/api/maintenance", "maintenance-mode", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: true }) }); }}>Enter Maintenance Mode</button></div></section></div> : null}
  </section>;
}

export function attentionItems(overview: Overview) { const items: Array<{ key: string; level: "attention" | "critical"; title: string; detail: string; action: string; taskId?: string }> = []; if (overview.overall === "critical") items.push({ key: "system", level: "critical", title: "System status is critical", detail: "Sandbox enforcement or a core system needs review.", action: overview.nextAction }); if (overview.reconcileRequired) items.push({ key: "reconcile", level: "attention", title: "Reconciliation required", detail: `${overview.reconcileRequired} operation${overview.reconcileRequired === 1 ? "" : "s"} require review.`, action: "Review reconciliation-required operations" }); if (overview.backup.level !== "ok") items.push({ key: "backup", level: "attention", title: "Backup needs review", detail: overview.backup.latest ? `Last verified backup was ${formatAge(overview.backup.latest.ageHours)} ago.` : "No verified backup exists.", action: "Create backup" }); if (overview.disk.level !== "ok") items.push({ key: "disk", level: "attention", title: "Disk capacity needs review", detail: `${formatBytes(overview.disk.freeBytes)} is free.`, action: "Review disk capacity" }); if (overview.providers.some((provider) => provider.level !== "ok")) items.push({ key: "providers", level: "attention", title: "Provider unavailable", detail: "One or more provider diagnostics are not ready.", action: "Review provider diagnostics" }); if (overview.worktrees.orphaned) items.push({ key: "worktrees", level: "attention", title: "Worktrees need inspection", detail: `${overview.worktrees.orphaned} orphaned or missing worktree${overview.worktrees.orphaned === 1 ? "" : "s"}.`, action: "Review orphaned worktrees" }); if (overview.outbound.failed || overview.outbound.ambiguous) items.push({ key: "slack", level: "attention", title: "Slack delivery needs review", detail: `${overview.outbound.failed} failed · ${overview.outbound.ambiguous} ambiguous.`, action: "Resolve Slack delivery" }); return items; }
function healthyCount(overview: Overview) { return [overview.database.status === "ok", overview.backup.level === "ok", overview.disk.level === "ok", overview.sandbox.status === "enforced", overview.providers.every((item) => item.level === "ok"), !overview.reconcileRequired].filter(Boolean).length; }
function providerName(value: string) { return value === "codex" ? "Codex" : value === "cursor" ? "Cursor" : value === "claude" ? "Claude" : value; } function shortId(value: string) { return `${value.slice(0, 8)}…`; } function formatBytes(value: number) { if (value >= 1024 ** 3) return `${(value / 1024 ** 3).toFixed(1)} GB`; if (value >= 1024 ** 2) return `${(value / 1024 ** 2).toFixed(1)} MB`; return `${Math.max(0, Math.ceil(value / 1024))} KB`; } function formatAge(hours: number) { return hours < 1 ? `${Math.max(0, Math.floor(hours * 60))} min` : hours < 48 ? `${Math.floor(hours)}h` : `${Math.floor(hours / 24)}d`; } function relativeTime(value: string) { return `${formatAge(Math.max(0, (Date.now() - Date.parse(value)) / 3_600_000))} ago`; }
